spring.application.name=Movie-Ticket-and-Reviewing-System
spring.datasource.url=jdbc:mysql://localhost:3306/shoutreview?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=vipul@ohh23

#logging.level.root=DEBUG

spring.jpa.show-sql=true

authority.admin=admin

##Hibernate Properties
# The SQL dialect makes Hibernate to generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
